[DEFAULT]
# SCHEDULER_ENABLED="True" or SCHEDULER_ENABLED="False"
SCHEDULER_ENABLED=TRUE  
# RUN_ENV_LOCAL="True" or RUN_ENV_LOCAL="False"
RUN_ENV_LOCAL="TRUE"  
# DOCKER_ENABLE="True" or DOCKER_ENABLE="False"
DOCKER_ENABLE="False"  
# JENKINS_ENABLE="True" or JENKINS_ENABLE="False"
JENKINS_ENABLE="False"  
# SECONDS=1200 will run every 1200 seconds
SECONDS=1200  
# Optional webhook / REST endpoint for forwarding execution logs
URL=
